name: Quarkiverse Perform Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Tag version to perform release
        required: true

permissions:
  attestations: write
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  perform-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "ARTIFACT_PATH=${{github.event.repository.name}}-${{github.event.inputs.version}}.zip" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.inputs.version}} # The tag created by the release:prepare goal

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Maven release ${{github.event.inputs.version}}
        run: |
          mvn deploy -DperformRelease -DaltDeploymentRepository=local::file://${{ github.workspace }}/repository # Deploy to a local repository
          cd ${{ github.workspace }}/repository
          zip -r ${{ github.workspace }}/$ARTIFACT_PATH .

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ${{env.ARTIFACT_PATH}}

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARTIFACT_PATH}}
          path: ${{env.ARTIFACT_PATH}}
          compression-level: 0
          retention-days: 1

