name: Quarkiverse Perform Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Tag version to perform release
        required: true

permissions:
  attestations: write
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  RELEASE_VERSION: ${{github.event.inputs.version}}

jobs:
  perform-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.inputs.version}} # The tag created by the release:prepare goal

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Maven release ${{needs.prepare-release.outputs.release_version}}
        run: |
          mvn deploy -DperformRelease -DaltDeploymentRepository=local::file://$RUNNER_TEMP/repository # Deploy to a local repository
          cd $RUNNER_TEMP/repository
          zip -r $RUNNER_TEMP/$GITHUB_REPOSITORY-$RELEASE_VERSION.zip .

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: $RUNNER_TEMP/$GITHUB_REPOSITORY-$RELEASE_VERSION.zip

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: released-binaries
          path: $RUNNER_TEMP/$GITHUB_REPOSITORY-$RELEASE_VERSION.zip
          retention-days: 1

