name: Quarkiverse Perform Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Tag version to perform release
        required: true

permissions:
  attestations: write
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  RELEASE_VERSION: ${{github.event.inputs.version}}
  ARTIFACT_PATH: ${{env.RUNNER_TEMP}}/${{env.GITHUB_REPOSITORY}}-${{env.RELEASE_VERSION}}.zip # Path to the artifact to be released

jobs:
  perform-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.inputs.version}} # The tag created by the release:prepare goal

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Maven release ${{needs.prepare-release.outputs.release_version}}
        run: |
          mkdir -p $RUNNER_TEMP/$GITHUB_REPOSITORY_OWNER # Create a directory to store the release binaries
          mvn deploy -DperformRelease -DaltDeploymentRepository=local::file://$RUNNER_TEMP/repository # Deploy to a local repository
          cd $RUNNER_TEMP/repository
          zip -r ${{env.ARTIFACT_PATH}} .

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ${{env.ARTIFACT_PATH}}

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: released-binaries
          path: ${{env.ARTIFACT_PATH}}
          retention-days: 1

